### ISSUE TITLE
Fatal error: Using $this when not in object context in CTXParser/src/php/CTXParser/Parser.php on line 156

### ISSUE THREAD

**Issue by NemoN** [kore/CTXParser#4]
php 5.3.28

$ php -f CTXParser/src/bin/parse output.ctx

Fatal error: Using $this when not in object context in CTXParser/src/php/CTXParser/Parser.php on line 156

**Comment by kore** [comment]
The CTXParser currently requires at least PHP 5.4.

I am not aware how much effort it would be to port it back to PHP 5.3 – if it does not mess up too much, I would accept a pull request for compatibility with PHP 5.3. But since my servers run PHP 5.4 or 5.5 I have no motivation to myself change that right now…

I documented the PHP requirement in the composer.json and issued a new minor release.

Thanks for your time to report a bug report, I am sorry, that there is no easy fix for this.
